### ISSUE TITLE
miniaudio

### ISSUE THREAD

**Issue by bjornbytes** [bjornbytes/lovr#302]
This issue tracks the work to replace OpenAL Soft with miniaudio.  miniaudio has a smaller footprint and allows for more control over audio rendering.

There is a party in the [`miniaudio-new`](https://github.com/bjornbytes/lovr/tree/miniaudio-new) branch and everyone is invited.

### TODO

Foundation

- [x] Create miniaudio context / devices
- [x] Let conf.lua decide which devices are initialized/autostarted.
- [x] `lovr.audio.start` and `lovr.audio.stop` lets you start/stop playback and capture devices.
- [x] `lovr.audio.reset` can be used to reset the devices to the defaults, in case the default device changed.
- [x] Master volume accessors.

Source

- [x] `Source` objects.
- [x] `Source:play`, `Source:pause`, `Source:stop`, `Source:isPlaying`.
- [x] `Source:getTime`, `Source:setTime`, `Source:getDuration`.
- [x] `Source:getVolume`, `Source:setVolume`.
- [x] `Source:isLooping`, `Source:setLooping`.
- [x] Mix multiple sources together in the playback callback.
- [x] Source automatically converts its Sound to the canonical format at mixtime when needed.

SoundData

- [x] `SoundData` objects.
- [x] `SoundData` from raw bytes (Blob plus format info).
- [x] `SoundData` from queue of Blobs or ring buffer (like raw AudioStream).
- [x] `SoundData` from audio file (Blob in audio file format).
  - [x] Support ogg format (stb_vorbis)
  - [x] Support wav format (#182, likely by hand, only supporting common WAV features)
  - [x] Support mp3 format (#259)
  - [x] Add `decode` option to immediately decode compressed audio stream files (replaces AudioStream/SourceType).

Spatialization

- [x] Create an interface for spatializer plugins, initialize them in `lovrAudioInit`.
- [x] Add `spatial` flag to Source.
- [x] Add spatializer hooks to the mixer.
- [ ] Determine reasonable superset of spatialization info needed by SteamAudio, Oculus Spatializer, WebAudio.
- [x] Add spatialization data to Source and audo module: struct fields, accessors, bindings.
- [ ] Learn about phonon (SteamAudio) and implement the phonon spatializer.

Capture

- [x] Implement capture device callback (API undecided).
- [x] Audio capture permission for Android

Side Quests

- [ ] Procedural Source backed by dumped Lua coroutine chunk that runs on audio thread.
- [ ] Use a Model or Mesh to back an environment mesh for audio occlusion/bounces.
- [x] Ability to change device performance profile preference
- [x] Device enumeration, introspection, stats.
- [ ] Ambisonics.

### Puzzles/Notes

- Should multiple playback devices be supported?  Currently only the default is used.  It would be great if you could detect if the default device changed but this doesn't appear to be possible.  At least `lovr.audio.reset` can be used.
- Should the capture API change?  Having to enumerate the microphone names and create objects for them felt kinda clunky to me.  On the branch right now it is set up to just use a single default capture device, but that is less powerful.  Some sort of middle  ground could be to let you query device names and change the device but not allow multiple devices.
- Source:seek/tell were renamed to getTime/setTime
- WebAudio -- miniaudio compiles to JS but won't support spatialization, could either modify miniaudio somehow or make a separate webaudio backend.
- miniaudio has duplex devices but at some point I decided to not use them
- Could we merge to dev branch before doing spatialization / side quests / etc.
- The thing I am most sad about right now is that we don't have a solution for getPitch/setPitch.
- Source should probably have something like `Source:getSoundData`

**Comment by nevyn** [comment]
I know both you and @mcclure are planning to tackle this -- anything aspect of it where I can help without getting in the way?

**Comment by bjornbytes** [comment]
Just updated the issue with the current status of things.  There's a few different areas so things could probably be parallelized.

**Comment by nevyn** [comment]
Thanks for the extremely thorough todo list!! Very helpful. I’ll likely dig into this after my current tasks.

**Comment by mcclure** [comment]
Here are some things I have implemented in other branches but not integrated. (Note that just because I have done them does not mean we should integrate my version instead of doing a new thing from scratch— these may not cleanly merge.)

- Oculus Audio support: I did this in a fork of the old "mixer" branch, however, I used a custom mixer different from the one Bjorn settled on: https://github.com/mcclure/lovr/blob/miniaudio-mixer/src/modules/audio/audio.c Branch is miniaudio-mixer

- "Procedural Source backed by dumped Lua coroutine chunk that runs on audio thread"— I have something like this in my RTmidi+portaudio branch. To try it check out [branch ZP_midi from my fork](https://github.com/mcclure/lovr/tree/ZP_midi). At the moment instead of using Sources properly the way it works is it has one generated "audio generator" thread. The audio callback then, if it has run out of audio to play, calls lua function [lovr.audio()](https://github.com/mcclure/lovr/blob/ZP_midi/game/audio/hook-audio.cpp#L149) in the thread. That lovr.audio() [returns a blob](https://github.com/mcclure/lovr/blob/ZP_midi/game/lua/midi/support/thread/helper/audio.lua#L19), and the blob is treated as pcm data and played. (There is a little oddness where lovr.audio() also receives a sample blob; the audio thread has the option of either reusing the blob as its storage or creating a new blob.) I'm not sure you'd want to do things the same way I did, but I do think it's good to give each procedural audio source its own Thread. This means (1) nice easy separation of concerns/namespaces and (2) it's easy and natural to communicate between threads using the Channel primitives. I have a larger demo showing complex commanding of an audio source using a Channel, in this demo the only thing I do with the channel is send a buffer back which is used to draw an oscilloscope. (I can post the larger demo— a granular synthesizer— if it helps but the problem with it is it has two copyrighted songs in the repo as ogg files and IDK how github will feel about that, lol)

**Comment by bjornbytes** [comment]
Rebased the branch so it's up to date with `dev` and updated it to build properly with CMake.

**Comment by bjornbytes** [comment]
Was thinking about capture

- `lovr.audio.getCaptureDuration`
  - Returns how much stuff is in the capture buffer (Microphone:getSampleCount but it accepts TimeUnit)
- `lovr.audio.capture([count], [dst], [dstOffset])`
  - Exactly like Microphone:getData
    - Should it also return number of samples written? (currently there is race condition between querying sample count and reading the samples)
- Whoa what if you can tell lovr.audio to pipe captured samples to a channel without needing to call .capture -> lower latency
  - Is this in addition to or instead of being able to call .capture
  - Is it dynamic getter/setter (setCaptureChannel), or something you do when starting the device.

**Comment by bjornbytes** [comment]
Placeholder note for supporting microphone permission requests (this sorta belongs more in a lovr.system module, but if/since that doesn't exist then lovr.audio bridging into core/os or something would be an acceptable workaround).

**Comment by nevyn** [comment]
@bjornbytes There is a `mix` function, and playing two sources simultaneously seems to work fine :) Anything in particular you want me to test before checking that one off?

**Comment by nevyn** [comment]
Got started at https://github.com/bjornbytes/lovr/pull/339 . The two things I'm the most nervous about are spatialization and mic capture. I'm feeling the waters re spatialization, but it seems you have very ambitious compatibility goals so I might not go all the way and risk going in the wrong direction, but I at least wanna try it out. Higher prio then is capture, because that's my main motivator for switching from openal anyway; get mic working on Quest.

@bjornbytes Re your thoughts on capture: I don't really mind the current API, but I also don't mind your suggestion of setting the input device in global state, and thus only allowing recording from a single device. I know iOS limits to one anyway, android might have similar restrictions.

Channel solution sounds cool but I'd prefer to KISS, which to me means starting with .capture() and adding a channel variant later.

**Comment by nevyn** [comment]
man, you sure you want me on this? looking at bjorn's code and mcclure's code, you two (especially you mcclure :O) are just waaaaaaaaaaaay better at audio than me? :S

**Comment by bjornbytes** [comment]
re mixer: it's good that it's working with 2 sources!  It's mostly the comments I left there that had me worried, I need to go over those carefully to make sure there wasn't an edge case left in.

I agree with adding the Channel stuff later if at all, definitely a side quest.

Also what!  I only really started getting into audio while working on this branch, I know nothing

**Comment by nevyn** [comment]
fair enough :sweat_smile: 

@bjornbytes Another question: `l_data_soundData` is empty -- anything in particular you were displeased about in that interface or did you have specific plans for it or did you just wipe everything when prepping for rewrite?

**Comment by nevyn** [comment]
testing this on Quest. 

you can't record audio on quest without first asking for permission; and the current code starts recording immediately; and either config failing will bring the audio subsystem down; so we'll need 1) explicit start/stop capture 2) audio permissions asap. digging in.

**Comment by bjornbytes** [comment]
We've got `lovr.audio.start` and `lovr.audio.stop` for explicit device control.  Would it be enough to call something like `lovrPlatformRequestAudioCapture` when the capture device tries to start and only start it if the permission request succeeds?  I think the JNI call is `requestRecordAudioPermission` on the activity.

**Comment by nevyn** [comment]
Hmmh then the developer can't be informed that capture has failed, since it's async. But maybe that's an alright first step, and then we can add explicit permissions check+ask code later. I'll also disable capture at start, so it needs to be explicitly enabled.

**Comment by mcclure** [comment]
You'll need some sort of idiom for a permissions request issue / permissions request result for other things in future as well, I suspect.

**Comment by bjornbytes** [comment]
These will go in the `lovr.system` module, but that doesn't exist yet so the workaround right now is to have it handled here internally.

**Comment by mcclure** [comment]
Right— sorry, what I mean is, you need to decide how success/failure is reported (a callback, a lovr.event, what). The permission check can move later but maybe it is good if when it moves the basic nature of interacting with it does not change.

**Comment by nevyn** [comment]
@bjornbytes Thanks for merging my capture and permissions work! <3 Glad to be moving this along :)

Tomorrow and rest of week I'll start doing audio streams and setting capture device. I'll also fix the math on the dummy spatializer. Once those are done, I think I'm at the limit of what I can productively contribute atm, and I'll leave the actual spatializer implementation to @mcclure and/or you (or until my next audio coding spree :P phonon looks amazing, would love to dig into it at some point).

**Comment by bjornbytes** [comment]
We have procedural audio streams now, thanks @nevyn!  The ring buffer is fancy

**Comment by bjornbytes** [comment]
The miniaudio branch is merged!  I'm still going to be adding a few minor improvements and working on the SteamAudio spatializer, but it's in a stable/usable state.  Thank you @nevyn and @mcclure for breathing life back into this!

**Comment by nevyn** [comment]
Thank you @bjornbytes for tying this all together!! Couldn't have been easy, getting all of those branches from three separate devs in! 

I think that was a pretty awesome collab from all three of us?! go us :D
